### ISSUE TITLE
[BUG]  or user error

### ISSUE THREAD

**Issue by tvanerp** [bids-apps/tracula#31]
### What version of the bids app were you using?

tracula-6.0.0-5.simg with bids 2.1.6 T1w and dwi data.

### Describe your problem in detail.

Created a singularity image from bids/tracula:latests

Running the following command:

Commandline: singularity run --cleanenv -B /dfs4/som/tvanerp_col/fbirn/bids_tracula:/data -B /tmp:/work -B /dfs4/som/tvanerp_col/fbirn/derivatives/tracula_singularity:/output -B /dfs4/som/tvanerp_col/fbirn/derivatives/freesurfer/7.1.1:/fsdir -B /data/opt/apps/freesurfer/7.1.1:/tmp /dfs4/som/tvanerp_col/bin/singularity_containers/tracula/tracula-6.0.0-5.simg --license_key /tmp/license.txt --participant_label 000300655084 --session_label 1 --freesurfer_dir /fsdir --stages all --n_cpus 8 /data /output participant

Am getting permission errors accessing the motion correction mat files:

mv -f /output/sub-000300655084/dmri/bvecs /output/sub-000300655084/dmri/bvecs.norot
xfmrot /output/sub-000300655084/dmri/dwi.ecclog /output/sub-000300655084/dmri/bvecs.norot /output/sub-000300655084/dmri/bvecs
/tmp/xfmrot.911707.mat: Permission denied.
Could not open matrix file /tmp/xfmrot.911707.mat
R: Subscript out of range.
R: Subscript out of range.
R: Subscript out of range.
/tmp/xfmrot.911707.mat: Permission denied.
Could not open matrix file /tmp/xfmrot.911707.mat
R: Subscript out of range.
R: Subscript out of range.
R: Subscript out of range.
...

Also permission error before processing stops:

/tmp/subj33.sub-000315778401.2339769.txt: Permission denied.

Error output shows the following:

Failed to import duecredit due to No module named 'duecredit'
Traceback (most recent call last):
  File "/code/run.py", line 78, in <module>
    participant_level(args, layout, subjects_to_analyze, args.session_label)
  File "/code/tracula.py", line 392, in participant_level
    run_tract_all(dmrirc_file, args.output_dir, subject_label, args.stages, args.n_cpus)
  File "/code/tracula.py", line 174, in run_tract_all
    run_trac_parallel(stage, jobs_dir, dmrirc_file, n_cpus, job_names=[""], sep=";")
  File "/code/tracula.py", line 162, in run_trac_parallel
    run_cmd(base_cmd)
  File "/code/tracula.py", line 27, in run_cmd
    raise Exception("Non zero return code: %d" % process.returncode)
Exception: Non zero return code: 1

### What command did you run?

Commandline: singularity run --cleanenv -B /dfs4/som/tvanerp_col/fbirn/bids_tracula:/data -B /tmp:/work -B /dfs4/som/tvanerp_col/fbirn/derivatives/tracula_singularity:/output -B /dfs4/som/tvanerp_col/fbirn/derivatives/freesurfer/7.1.1:/fsdir -B /data/opt/apps/freesurfer/7.1.1:/tmp /dfs4/som/tvanerp_col/bin/singularity_containers/tracula/tracula-6.0.0-5.simg --license_key /tmp/license.txt --participant_label 000300655084 --session_label 1 --freesurfer_dir /fsdir --stages all --n_cpus 8 /data /output participant

### Describe what you expected.

Expected tracula to run to completion without errors.

**Comment by tvanerp** [comment]
Figured out the issue: user error - changed -B /tmp:/work to /tmp:/tmp and /data/opt/apps/freesurfer/7.1.1:/tmp to /data/opt/apps/freesurfer/7.1.1:/sf and tracula finished without errors.
